// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/client/Servermsg.proto

package com.example.tutorial;

public final class Servermsg {
  private Servermsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ServermsgsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string msg = 1;
    /**
     * <code>optional string msg = 1;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 1;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    // repeated .Servermsgs contact = 2;
    /**
     * <code>repeated .Servermsgs contact = 2;</code>
     */
    java.util.List<com.example.tutorial.Servermsg.Servermsgs> 
        getContactList();
    /**
     * <code>repeated .Servermsgs contact = 2;</code>
     */
    com.example.tutorial.Servermsg.Servermsgs getContact(int index);
    /**
     * <code>repeated .Servermsgs contact = 2;</code>
     */
    int getContactCount();
    /**
     * <code>repeated .Servermsgs contact = 2;</code>
     */
    java.util.List<? extends com.example.tutorial.Servermsg.ServermsgsOrBuilder> 
        getContactOrBuilderList();
    /**
     * <code>repeated .Servermsgs contact = 2;</code>
     */
    com.example.tutorial.Servermsg.ServermsgsOrBuilder getContactOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Servermsgs}
   */
  public static final class Servermsgs extends
      com.google.protobuf.GeneratedMessage
      implements ServermsgsOrBuilder {
    // Use Servermsgs.newBuilder() to construct.
    private Servermsgs(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Servermsgs(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Servermsgs defaultInstance;
    public static Servermsgs getDefaultInstance() {
      return defaultInstance;
    }

    public Servermsgs getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Servermsgs(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              msg_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                contact_ = new java.util.ArrayList<com.example.tutorial.Servermsg.Servermsgs>();
                mutable_bitField0_ |= 0x00000002;
              }
              contact_.add(input.readMessage(com.example.tutorial.Servermsg.Servermsgs.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          contact_ = java.util.Collections.unmodifiableList(contact_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.tutorial.Servermsg.internal_static_Servermsgs_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.tutorial.Servermsg.internal_static_Servermsgs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.tutorial.Servermsg.Servermsgs.class, com.example.tutorial.Servermsg.Servermsgs.Builder.class);
    }

    public static com.google.protobuf.Parser<Servermsgs> PARSER =
        new com.google.protobuf.AbstractParser<Servermsgs>() {
      public Servermsgs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Servermsgs(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Servermsgs> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string msg = 1;
    public static final int MSG_FIELD_NUMBER = 1;
    private java.lang.Object msg_;
    /**
     * <code>optional string msg = 1;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string msg = 1;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .Servermsgs contact = 2;
    public static final int CONTACT_FIELD_NUMBER = 2;
    private java.util.List<com.example.tutorial.Servermsg.Servermsgs> contact_;
    /**
     * <code>repeated .Servermsgs contact = 2;</code>
     */
    public java.util.List<com.example.tutorial.Servermsg.Servermsgs> getContactList() {
      return contact_;
    }
    /**
     * <code>repeated .Servermsgs contact = 2;</code>
     */
    public java.util.List<? extends com.example.tutorial.Servermsg.ServermsgsOrBuilder> 
        getContactOrBuilderList() {
      return contact_;
    }
    /**
     * <code>repeated .Servermsgs contact = 2;</code>
     */
    public int getContactCount() {
      return contact_.size();
    }
    /**
     * <code>repeated .Servermsgs contact = 2;</code>
     */
    public com.example.tutorial.Servermsg.Servermsgs getContact(int index) {
      return contact_.get(index);
    }
    /**
     * <code>repeated .Servermsgs contact = 2;</code>
     */
    public com.example.tutorial.Servermsg.ServermsgsOrBuilder getContactOrBuilder(
        int index) {
      return contact_.get(index);
    }

    private void initFields() {
      msg_ = "";
      contact_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMsgBytes());
      }
      for (int i = 0; i < contact_.size(); i++) {
        output.writeMessage(2, contact_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMsgBytes());
      }
      for (int i = 0; i < contact_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, contact_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.tutorial.Servermsg.Servermsgs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.tutorial.Servermsg.Servermsgs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.tutorial.Servermsg.Servermsgs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.tutorial.Servermsg.Servermsgs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.tutorial.Servermsg.Servermsgs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.tutorial.Servermsg.Servermsgs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.tutorial.Servermsg.Servermsgs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.tutorial.Servermsg.Servermsgs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.tutorial.Servermsg.Servermsgs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.tutorial.Servermsg.Servermsgs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.tutorial.Servermsg.Servermsgs prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Servermsgs}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.tutorial.Servermsg.ServermsgsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.tutorial.Servermsg.internal_static_Servermsgs_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.tutorial.Servermsg.internal_static_Servermsgs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.tutorial.Servermsg.Servermsgs.class, com.example.tutorial.Servermsg.Servermsgs.Builder.class);
      }

      // Construct using com.example.tutorial.Servermsg.Servermsgs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getContactFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (contactBuilder_ == null) {
          contact_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          contactBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.tutorial.Servermsg.internal_static_Servermsgs_descriptor;
      }

      public com.example.tutorial.Servermsg.Servermsgs getDefaultInstanceForType() {
        return com.example.tutorial.Servermsg.Servermsgs.getDefaultInstance();
      }

      public com.example.tutorial.Servermsg.Servermsgs build() {
        com.example.tutorial.Servermsg.Servermsgs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.tutorial.Servermsg.Servermsgs buildPartial() {
        com.example.tutorial.Servermsg.Servermsgs result = new com.example.tutorial.Servermsg.Servermsgs(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msg_ = msg_;
        if (contactBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            contact_ = java.util.Collections.unmodifiableList(contact_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.contact_ = contact_;
        } else {
          result.contact_ = contactBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.tutorial.Servermsg.Servermsgs) {
          return mergeFrom((com.example.tutorial.Servermsg.Servermsgs)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.tutorial.Servermsg.Servermsgs other) {
        if (other == com.example.tutorial.Servermsg.Servermsgs.getDefaultInstance()) return this;
        if (other.hasMsg()) {
          bitField0_ |= 0x00000001;
          msg_ = other.msg_;
          onChanged();
        }
        if (contactBuilder_ == null) {
          if (!other.contact_.isEmpty()) {
            if (contact_.isEmpty()) {
              contact_ = other.contact_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureContactIsMutable();
              contact_.addAll(other.contact_);
            }
            onChanged();
          }
        } else {
          if (!other.contact_.isEmpty()) {
            if (contactBuilder_.isEmpty()) {
              contactBuilder_.dispose();
              contactBuilder_ = null;
              contact_ = other.contact_;
              bitField0_ = (bitField0_ & ~0x00000002);
              contactBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getContactFieldBuilder() : null;
            } else {
              contactBuilder_.addAllMessages(other.contact_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.tutorial.Servermsg.Servermsgs parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.tutorial.Servermsg.Servermsgs) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string msg = 1;
      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 1;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string msg = 1;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 1;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 1;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 1;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msg_ = value;
        onChanged();
        return this;
      }

      // repeated .Servermsgs contact = 2;
      private java.util.List<com.example.tutorial.Servermsg.Servermsgs> contact_ =
        java.util.Collections.emptyList();
      private void ensureContactIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          contact_ = new java.util.ArrayList<com.example.tutorial.Servermsg.Servermsgs>(contact_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.tutorial.Servermsg.Servermsgs, com.example.tutorial.Servermsg.Servermsgs.Builder, com.example.tutorial.Servermsg.ServermsgsOrBuilder> contactBuilder_;

      /**
       * <code>repeated .Servermsgs contact = 2;</code>
       */
      public java.util.List<com.example.tutorial.Servermsg.Servermsgs> getContactList() {
        if (contactBuilder_ == null) {
          return java.util.Collections.unmodifiableList(contact_);
        } else {
          return contactBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Servermsgs contact = 2;</code>
       */
      public int getContactCount() {
        if (contactBuilder_ == null) {
          return contact_.size();
        } else {
          return contactBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Servermsgs contact = 2;</code>
       */
      public com.example.tutorial.Servermsg.Servermsgs getContact(int index) {
        if (contactBuilder_ == null) {
          return contact_.get(index);
        } else {
          return contactBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Servermsgs contact = 2;</code>
       */
      public Builder setContact(
          int index, com.example.tutorial.Servermsg.Servermsgs value) {
        if (contactBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactIsMutable();
          contact_.set(index, value);
          onChanged();
        } else {
          contactBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Servermsgs contact = 2;</code>
       */
      public Builder setContact(
          int index, com.example.tutorial.Servermsg.Servermsgs.Builder builderForValue) {
        if (contactBuilder_ == null) {
          ensureContactIsMutable();
          contact_.set(index, builderForValue.build());
          onChanged();
        } else {
          contactBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Servermsgs contact = 2;</code>
       */
      public Builder addContact(com.example.tutorial.Servermsg.Servermsgs value) {
        if (contactBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactIsMutable();
          contact_.add(value);
          onChanged();
        } else {
          contactBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Servermsgs contact = 2;</code>
       */
      public Builder addContact(
          int index, com.example.tutorial.Servermsg.Servermsgs value) {
        if (contactBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactIsMutable();
          contact_.add(index, value);
          onChanged();
        } else {
          contactBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Servermsgs contact = 2;</code>
       */
      public Builder addContact(
          com.example.tutorial.Servermsg.Servermsgs.Builder builderForValue) {
        if (contactBuilder_ == null) {
          ensureContactIsMutable();
          contact_.add(builderForValue.build());
          onChanged();
        } else {
          contactBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Servermsgs contact = 2;</code>
       */
      public Builder addContact(
          int index, com.example.tutorial.Servermsg.Servermsgs.Builder builderForValue) {
        if (contactBuilder_ == null) {
          ensureContactIsMutable();
          contact_.add(index, builderForValue.build());
          onChanged();
        } else {
          contactBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Servermsgs contact = 2;</code>
       */
      public Builder addAllContact(
          java.lang.Iterable<? extends com.example.tutorial.Servermsg.Servermsgs> values) {
        if (contactBuilder_ == null) {
          ensureContactIsMutable();
          super.addAll(values, contact_);
          onChanged();
        } else {
          contactBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Servermsgs contact = 2;</code>
       */
      public Builder clearContact() {
        if (contactBuilder_ == null) {
          contact_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          contactBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Servermsgs contact = 2;</code>
       */
      public Builder removeContact(int index) {
        if (contactBuilder_ == null) {
          ensureContactIsMutable();
          contact_.remove(index);
          onChanged();
        } else {
          contactBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Servermsgs contact = 2;</code>
       */
      public com.example.tutorial.Servermsg.Servermsgs.Builder getContactBuilder(
          int index) {
        return getContactFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Servermsgs contact = 2;</code>
       */
      public com.example.tutorial.Servermsg.ServermsgsOrBuilder getContactOrBuilder(
          int index) {
        if (contactBuilder_ == null) {
          return contact_.get(index);  } else {
          return contactBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Servermsgs contact = 2;</code>
       */
      public java.util.List<? extends com.example.tutorial.Servermsg.ServermsgsOrBuilder> 
           getContactOrBuilderList() {
        if (contactBuilder_ != null) {
          return contactBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(contact_);
        }
      }
      /**
       * <code>repeated .Servermsgs contact = 2;</code>
       */
      public com.example.tutorial.Servermsg.Servermsgs.Builder addContactBuilder() {
        return getContactFieldBuilder().addBuilder(
            com.example.tutorial.Servermsg.Servermsgs.getDefaultInstance());
      }
      /**
       * <code>repeated .Servermsgs contact = 2;</code>
       */
      public com.example.tutorial.Servermsg.Servermsgs.Builder addContactBuilder(
          int index) {
        return getContactFieldBuilder().addBuilder(
            index, com.example.tutorial.Servermsg.Servermsgs.getDefaultInstance());
      }
      /**
       * <code>repeated .Servermsgs contact = 2;</code>
       */
      public java.util.List<com.example.tutorial.Servermsg.Servermsgs.Builder> 
           getContactBuilderList() {
        return getContactFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.tutorial.Servermsg.Servermsgs, com.example.tutorial.Servermsg.Servermsgs.Builder, com.example.tutorial.Servermsg.ServermsgsOrBuilder> 
          getContactFieldBuilder() {
        if (contactBuilder_ == null) {
          contactBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.example.tutorial.Servermsg.Servermsgs, com.example.tutorial.Servermsg.Servermsgs.Builder, com.example.tutorial.Servermsg.ServermsgsOrBuilder>(
                  contact_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          contact_ = null;
        }
        return contactBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Servermsgs)
    }

    static {
      defaultInstance = new Servermsgs(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Servermsgs)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Servermsgs_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Servermsgs_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032src/client/Servermsg.proto\"7\n\nServerms" +
      "gs\022\013\n\003msg\030\001 \001(\t\022\034\n\007contact\030\002 \003(\0132\013.Serve" +
      "rmsgsB!\n\024com.example.tutorialB\tServermsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Servermsgs_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Servermsgs_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Servermsgs_descriptor,
              new java.lang.String[] { "Msg", "Contact", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
